In [11]:
import pandas as pd

In [12]:
df_csv = pd.read_csv("../otherfiles/sample_data.csv")

In [13]:
print(df_csv)

   id       name              email      city
0   1      maria    maria@gmail.com   chicago
1   2       john   john@outlook.com    dallas
2   3        dan      dan@yahoo.com   atlanta
3   4   fernando      fnd@gmail.com  san jose
4   5  christine  christine@xyz.com   memphis

To view metadata information

In [ ]:
# info() gives entire information about the dataframe.

df_csv.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      5 non-null      int64
 1   name    5 non-null      str
 2   email   5 non-null      str
 3   city    5 non-null      str
dtypes: int64(1), str(3)
memory usage: 292.0 bytes

In [14]:
# To view metadata
df_csv.columns

Index(['id', 'name', 'email', 'city'], dtype='str')

In [15]:
print(df_csv.columns)

Index(['id', 'name', 'email', 'city'], dtype='str')

In [16]:
print(df_csv.dtypes)

id       int64
name       str
email      str
city       str
dtype: object

In [ ]:
# Returns number of records and columns 
# 5, 4 --> 5 are records and 4 are columns

df_csv.shape

(5, 4)

In [17]:
df_csv.head(10)

   id       name              email      city
0   1      maria    maria@gmail.com   chicago
1   2       john   john@outlook.com    dallas
2   3        dan      dan@yahoo.com   atlanta
3   4   fernando      fnd@gmail.com  san jose
4   5  christine  christine@xyz.com   memphis

In [18]:
df_csv

   id       name              email      city
0   1      maria    maria@gmail.com   chicago
1   2       john   john@outlook.com    dallas
2   3        dan      dan@yahoo.com   atlanta
3   4   fernando      fnd@gmail.com  san jose
4   5  christine  christine@xyz.com   memphis

In [20]:
df_csv.tail(10)

   id       name              email      city
0   1      maria    maria@gmail.com   chicago
1   2       john   john@outlook.com    dallas
2   3        dan      dan@yahoo.com   atlanta
3   4   fernando      fnd@gmail.com  san jose
4   5  christine  christine@xyz.com   memphis